# Generated by Django 2.2.5 on 2020-02-09 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crypto', '0004_auto_20200209_1509'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=225, null=True)),
                ('slug', models.SlugField(blank=True, default='')),
            ],
        ),
        migrations.DeleteModel(
            name='Snippest',
        ),
    ]
