# Generated by Django 2.2.5 on 2020-04-07 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crypto', '0005_auto_20200209_1951'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contactmodel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=50)),
                ('messages', models.CharField(max_length=1000)),
            ],
        ),
    ]
